name: django-gis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal=3.9
  - geos=3.12
  - proj
  - geotiff
  - libspatialite
  - sqlite
  - pip
  - pip:
      - django==5.2
      - djangorestframework==3.16.0
      - djangorestframework-gis==1.2.0
      - djangorestframework-simplejwt==5.5.0
      - django-filter==25.1
      - django-widget-tweaks==1.5.0
      - pillow
      - psycopg2-binary
      - gunicorn
      - dj-database-url==2.1.0
      - whitenoise==6.6.0


