name: django-gis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal
  - geos
  - proj
  - geotiff
  - libspatialite
  - sqlite
  - pip
  - pip:
      - django==5.2
      - djangorestframework==3.16.0
      - djangorestframework-gis==1.2.0
      - djangorestframework-simplejwt==5.5.0
      - django-filter==25.1
      - django-widget-tweaks==1.5.0
      - pillow
      - psycopg2
      - gunicorn
# prefix: C:\Users\maria\.conda\envs\django-gis


# para actualizar documento - conda env export > environment.yml
# conda activate django-gis - para activar entorno
# conda env create -f environment.yml - para crear entorno en otro computador