name: django-gis
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.21.6=h4190f5b_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - freeglut=3.4.0=h8a1e904_1
  - freexl=2.0.0=hd7a5696_0
  - gdal=3.11.0=py311h30179e3_1
  - geos=3.10.6=he74ecf9_0
  - geotiff=1.7.0=hbf7d8e7_4
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9e=h827c3e9_3
  - lerc=4.0.0=h5da7b33_0
  - libarchive=3.7.7=h9243413_0
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal-core=3.11.0=he0406c8_1
  - libiconv=1.16=h2bbff1b_3
  - libkml=1.3.0=h63940dd_7
  - libpng=1.6.39=h8cc25b3_0
  - libspatialite=5.1.0=h6715bb4_2
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - minizip=4.0.3=hb68bac4_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.4.0=py311h827c3e9_3
  - mkl_fft=1.3.11=py311h5810407_1
  - mkl_random=1.2.8=py311h8683371_1
  - numpy=2.3.3=py311hc2e1e29_0
  - numpy-base=2.3.3=py311hc851d2b_0
  - openssl=3.0.17=h35632f6_0
  - pcre2=10.42=h0ff8eda_1
  - pip=25.2=pyhc872135_0
  - proj=9.3.1=h4c8f42b_1
  - python=3.11.13=h981015d_0
  - setuptools=72.1.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - uriparser=0.9.8=h1a0bd13_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xerces-c=3.2.4=hd77b12b_1
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - asgiref==3.8.1
      - django==5.2
      - django-filter==25.1
      - django-widget-tweaks==1.5.0
      - djangorestframework==3.16.0
      - djangorestframework-gis==1.2.0
      - djangorestframework-simplejwt==5.5.0
      - pillow==11.2.1
      - postgis==1.0.4
      - psycopg2==2.9.10
      - pyjwt==2.9.0
      - sqlparse==0.5.3
      - tzdata==2025.2
prefix: C:\Users\maria\.conda\envs\django-gis


# para actualizar documento - conda env export > environment.yml
# conda activate django-gis - para activar entorno
# conda env create -f environment.yml - para crear entorno en otro computador