name: django-gis
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.21.6=h85f69ea_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - expat=2.7.3=hac47afa_0
  - freeglut=3.4.0=h8a1e904_1
  - freexl=2.0.0=hf297d47_2
  - gdal=3.9.3=py311ha2c19c5_19
  - geos=3.13.0=h5a68840_0
  - geotiff=1.7.4=h887f4e7_0
  - intel-openmp=2025.3.0=h57928b3_641
  - krb5=1.21.3=hdf4eb48_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.7.7=h88ece9c_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libgdal-core=3.9.3=ha193a43_8
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libkml=1.3.0=h68a222c_1022
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.51=h7351971_0
  - librttopo=1.1.0=hd4c2148_17
  - libspatialite=5.1.0=h939089a_12
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=hdefb170_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=h29ce207_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2025.2.0=hac47afa_628
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - numpy=2.3.3=py311hc2e1e29_0
  - numpy-base=2.3.3=py311hc851d2b_0
  - openssl=3.6.0=h725018a_0
  - pcre2=10.44=h99c9b8b_2
  - pip=25.3=pyh8b19718_0
  - proj=9.5.1=h4f671f6_0
  - python=3.11.14=h0159041_2_cpython
  - python_abi=3.11=8_cp311
  - setuptools=73.0.1=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sqlite=3.51.1=hdb435a2_0
  - tbb=2022.3.0=hd094cb3_1
  - tbb-devel=2022.3.0=h4eb897c_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.26100.0=h57928b3_0
  - uriparser=0.9.8=h5a68840_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=he0c23c2_2
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h1b5488d_4
  - pip:
      - asgiref==3.8.1
      - brotli==1.2.0
      - dj-database-url==3.0.1
      - django==5.2
      - django-environ==0.12.0
      - django-filter==25.1
      - django-widget-tweaks==1.5.0
      - djangorestframework==3.16.0
      - djangorestframework-gis==1.2.0
      - djangorestframework-simplejwt==5.5.0
      - gunicorn==23.0.0
      - packaging==25.0
      - pillow==11.2.1
      - postgis==1.0.4
      - psycopg2==2.9.10
      - psycopg2-binary==2.9.11
      - pyjwt==2.9.0
      - sqlparse==0.5.3
      - tzdata==2025.2
      - whitenoise==6.11.0
prefix: C:\Users\maria\.conda\envs\django-gis
